# Generated by Django 3.2.5 on 2021-09-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_only', '0004_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
