# Generated by Django 3.2.5 on 2021-09-15 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_only', '0005_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='app_only.user'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upload_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneaker_comments', to='app_only.sneaker'),
        ),
        migrations.AlterField(
            model_name='image',
            name='posted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_images', to='app_only.user'),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sneaker_images', to='app_only.sneaker'),
        ),
    ]
